import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Container from "@mui/material/Container/Container";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container maxWidth="sm" sx={{ backgroundColor: 'white', minWidth: '360px' }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
