import type { Metadata } from "next";
import { Hahmlet } from "next/font/google";
import Container from "@mui/material/Container/Container";
import "./globals.css";
import GlobalStyles from "@mui/material/GlobalStyles";

const hahmlet = Hahmlet({
  subsets: ['latin'],
  variable: '--font-hahmlet',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hahmlet.className} ${hahmlet.variable}`}>
        <Container maxWidth="sm" sx={{ backgroundColor: 'white', minWidth: '360px' }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
